### ISSUE TITLE
Half ot the screen is black

### ISSUE THREAD

**Issue by antoshayastreb** [blake502/balatro-apk-maker#1] opened 2024-03-29 10:00 UTC
Hi, i have some strange behavior and doesn't know if this related to this repo specific or love-android port. When i launching game on Pixel 7a half of my screan covered with black . It's also woth mentiong that other devices that i have tested doesn't have this issiue. It's not related to pathes, since removing or adding them doesn't changing anything.

![photo_2024-03-28_23-32-53](https://github.com/blake502/balatro-apk-maker/assets/34381227/4983553a-ef81-4fe8-84a7-e709075867c4)

**Comment by tip0un3** [comment] 2024-03-29 10:50
Same problem with a Pixel 6A. I think it's related to the hardware, since according to community feedback, all Pixels have had this problem since version 6. Probably due to the Google Tensor chip. I've also tested an APK on a modding site and emulation with "LÖVE" app, the black spot is still there. I'm following the topic, if anyone would solve the problem or know a fix?

**Comment by asturle** [comment] 2024-03-29 19:52
Also echoing the same problem on a Pixel 6A, half of the screen is black on portrait and landscape.

**Comment by jojobozo** [comment] 2024-03-29 23:55
Same issue on my Pixel 7

**Comment by blake502** [comment] 2024-03-30 00:25
I'm aware of the issue on Pixel devices. Unfortunately, I do not have a Pixel device to troubleshoot this issue. I'll see whether a Pixel emulator will reproduce the issue.
I'll gladly update the repo if somebody can produce a fix on their own before me. I'll accept a pull request if you have the patience to deal with my messy patch functions.

**Comment by blake502** [comment] 2024-03-30 00:32
> Same problem with a Pixel 6A. I think it's related to the hardware, since according to community feedback, all Pixels have had this problem since version 6. Probably due to the Google Tensor chip. I've also tested a different APK and emulation with "LÖVE" app, the black spot is still there. I'm following the topic, if anyone would solve the problem or know a fix?

While I'm thankful for this information... let's be careful discussing less-than-legal methods of obtaining a Balatro APK.

**Comment by blake502** [comment] 2024-03-30 00:39
![image](https://github.com/blake502/balatro-apk-maker/assets/102875455/c121bf05-2fe2-4fe1-8af5-c6570865f83b)
I was not able to reproduce the issue with the Pixel 7a emulator.

**Comment by blake502** [comment] 2024-03-30 00:44
Question-- does the black oval appear during the splash screen when you first launch the game? Or does it only appear once you get to the main menu?

**Comment by asturle** [comment] 2024-03-30 01:31
Its on the opening splash screen and persists through the game.

**Comment by hub-bat** [comment] 2024-03-30 09:33
Out of curiosity, what version of Android is the Pixel 7a emulator running? I'm on the latest update of Android 14 and experiencing the issue on the 6a.

**Comment by jSchmiez** [comment] 2024-03-30 16:26
I'm using a pixel 8 running Android 14 and have this issue. I also tested the same APK on a 2023 razr plus on Android 13 and that works fine. Also tried it on a pixel 7 pro on Android 14 and that also has the black oval. So I'm inclined to think this is something Tensor specific.

**Comment by jojobozo** [comment] 2024-03-30 18:23
Apparently someone faced the same issue on a tablet with MTK

**Comment by blake502** [comment] 2024-03-31 00:23
Would somebody be available for some real-time testing with me over Discord? I've located a few things in the source code that could potentially be the problem-- but it's impossible for me to test on my own.

**Comment by jSchmiez** [comment] 2024-03-31 16:43
I know it's Easter, but I got time to help you out today if you want. My username is jschmiez

**Comment by Zeustit** [comment] 2024-04-01 07:58
Pixel 8 same thing

**Comment by rkyung** [comment] 2024-04-01 12:05
If it helps any, when I run an old packaged apk of the 1.0.0-L version of balatro it runs fine. The 1.0.0-N has the black oval. I'm on a pixel 6 pro

**Comment by jojobozo** [comment] 2024-04-01 18:22
> If it helps any, when I run an old packaged apk of the 1.0.0-L version of balatro it runs fine. The 1.0.0-N has the black oval. I'm on a pixel 6 pro

I'm not finding it, can you share the apk? My discord is waldooooo_

**Comment by hub-bat** [comment] 2024-04-01 18:27
Please do not share APKs. It's still piracy to do so and goes against TOS. You can rollback a steam game, so try and that and package your own APK.

**Comment by EvoSteven** [comment] 2024-04-01 20:59
Using the steam console, you can download older versions. Something like "download_depot 2379780 2379781 <manifest-id>", you can easily find the ids on steamdb.info .
I was not able to reproduce an older version not having the issue on the Pixel 8. I tried 1.0.0 N, L and even K, all broken.

**Comment by rkyung** [comment] 2024-04-02 05:50
Ok I remembered what I did to fix this. Line 2881 of the game.lua file

`        love.graphics.setShader( G.SHADERS['CRT']) `

if you just disable/remove this line the black "oval" goes away on Pixel phones.

**Comment by EvoSteven** [comment] 2024-04-02 08:24
> Ok I remembered what I did to fix this. Line 2881 of the game.lua file
> 
> ` love.graphics.setShader( G.SHADERS['CRT'])`
> 
> if you just disable/remove this line and the black "oval" goes away on Pixel phones.
> 
> FWIW: I also applied all four patches.

That worked for me as well!

**Comment by jojobozo** [comment] 2024-04-02 09:49
> Ok I remembered what I did to fix this. Line 2881 of the game.lua file
> 
> ` love.graphics.setShader( G.SHADERS['CRT'])`
> 
> if you just disable/remove this line and the black "oval" goes away on Pixel phones.
> 
> FWIW: I also applied all four patches.

Thanks!

**Comment by tip0un3** [comment] 2024-04-02 13:32
> Ok I remembered what I did to fix this. Line 2881 of the game.lua file
> 
> ` love.graphics.setShader( G.SHADERS['CRT'])`
> 
> if you just disable/remove this line and the black "oval" goes away on Pixel phones.
> 
> FWIW: I also applied all four patches.

Thank you very much. Works perfectly on Pixel 6A with this removal.

**Comment by blake502** [comment] 2024-04-02 13:50
> Ok I remembered what I did to fix this. Line 2881 of the game.lua file
> 
> ` love.graphics.setShader( G.SHADERS['CRT'])`
> 
> if you just disable/remove this line and the black "oval" goes away on Pixel phones.
> 
> FWIW: I also applied all four patches.

Thanks for this! I _knew_ the CRT shader was to blame haha. I'll apply that to the CRT disable patch!

**Comment by blake502** [comment] 2024-04-02 14:18
This has been updated in the [latest release](https://github.com/blake502/balatro-apk-maker/releases/download/beta-0.2/balatro-apk-maker-beta-0.2.exe). Anybody wanna try it to make sure before I close this issue?

**Comment by jSchmiez** [comment] 2024-04-02 14:23
yep that fixed it for my pixel 8

**Comment by rkyung** [comment] 2024-04-03 00:52
> > Ok I remembered what I did to fix this. Line 2881 of the game.lua file
> > ` love.graphics.setShader( G.SHADERS['CRT'])`
> > if you just disable/remove this line and the black "oval" goes away on Pixel phones.
> > FWIW: I also applied all four patches.
> 
> Thanks for this! I _knew_ the CRT shader was to blame haha. I'll apply that to the CRT disable patch!

No doubt about it. You probably had way better approach with our the proper hardware, other than the way I did it, semi-brute force figure out what needed to change.

**Comment by asturle** [comment] 2024-04-03 04:20
> This has been updated in the [latest release](https://github.com/blake502/balatro-apk-maker/releases/download/beta-0.2/balatro-apk-maker-beta-0.2.exe). Anybody wanna try it to make sure before I close this issue?

Great news, this fixed it on my 6A! Awesome work!

**Closed** 2024-04-03 22:13 UTC

**Comment by lu2000luk** [comment] 2025-08-08 12:52
Still happens on CMF Phone 1 (all patches enabled, modded)
